name = "ShopSchedulr Theme Block"
handle = "shopschedulr-theme-block"
uid = "cf9a04f9-93ad-f0a3-3d7f-3c4ccc60adaf0791c5f7"
type = "theme"

[build]
command = ""

[extension_points]
# This enables theme blocks/sections

